- hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  tasks:
    - name: Create resource group team4rg
      azure_rm_resourcegroup:
        name: team4rg
        location: westus
      register: rg_result

    - name: Résumé création
      debug:
        msg: "Resource group team4rg créé ou déjà existant. changed={{ rg_result.changed }}"
