- name: Create Azure VM
  hosts: localhost
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: team4rg
      location: francecentral
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: team4rg
      name: myVnet
      location:  francecentral
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: team4rg
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: team4rg
      allocation_method: Static
      name: myPublicIP1
      sku: Standard  
      location:  francecentral

    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: team4rg
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: springboot
          protocol: https
          destination_port_range: 8080
          access: Allow
          priority: 1001
          direction: Inbound  
        
  - name: Create a network interface using existing security group and public IP
    azure_rm_networkinterface:
      name: myNIC
      resource_group: team4rg
      virtual_network: myVnet
      subnet_name: mySubnet
      security_group: myNetworkSecurityGroup
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: myPublicIP1
          primary: true
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: team4rg
      name: myVM
      vm_size: Standard_B2ats_v2
      admin_username: azureuser
      admin_password: "teamteam4@"
      managed_disk_type: Standard_LRS  
      network_interfaces: myNIC
      image:
        offer: ubuntu-22_04-lts
        publisher: Canonical
        sku: server
        version: latest