- name: Delete a resource group
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - name: supprimer resource group team4rg    
      azure_rm_resourcegroup:
        name: team4rg
        state: absent
        force_delete_nonempty: true
